name: npm-publish

on:
#  release:
#    types: [registry_package]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: export NPM_CONFIG_SCOPE=""
      - run: npm install
      - run: npm install typescript@'<3.9.0' 
      - run: rm .npmrc
      - run: sed -i 's:@timurxyz/statefuld:statefuld:' src/package.json
      - run: npm run build:lib
      - run: npm publish src/dist --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
