name: npm-publish

on:
  registry_package:
    action:
          - published
          - updated
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      # hack for the current version's problem
      - run: yarn add typescript@'<3.9.0' 
      - run: sed -i 's:@timurxyz/statefuld:statefuld:' ./src.statefuld/package.json
      - run: yarn build:npmjs
      - run: npm publish ./src.statefuld/dist --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
